#!/usr/bin/python3

import argparse
import configparser
import subprocess
from os import environ
from pathlib import Path

cfg_locations = [
    "/etc/topydo.conf",
    str(Path("~/.config/topydo/config").expanduser()),
    str(Path("~/.topydo").expanduser()),
    ".topydo",
    "topydo.conf",
    "topydo.ini",
]


def main():
    config = configparser.ConfigParser()
    config.read(cfg_locations)
    print(config.get("topydo", "filename", fallback="todo.txt"))


main()
